#!/usr/bin/env python3
"""Build one self-contained game executable: suyu-cmd with the AOT modules linked in statically.

Steps (the same contract suyu's "build" export format uses, src/suyu/game_export.cpp):
  1. write recomp_registration.c and the ABI marker headers next to the exported modules
     (module list from aot_manifest.json, NSO load order rtld, main, subsdk0-9, sdk);
  2. configure a separate suyu tree with SUYU_CMD_RECOMP_DIR pointing at them, without the JIT
     (SUYU_NO_JIT=ON) and strict static by default;
  3. build target suyu-cmd-static (C++ host with the project compiler, generated C with clang).

The exporter's own build step runs inside the Qt dialog with the default C compiler and no memory
control; this does the build here instead (clang, object cache, bounded parallelism).

  python3 scripts/package-standalone.py [--hybrid] [--jobs 4] [--recomp-jobs 2] [--configure-only]
"""
import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
import lab  # noqa: E402
import plat  # noqa: E402

LOAD_ORDER = ['rtld', 'main'] + [f'subsdk{i}' for i in range(10)] + ['sdk']


def ordered(modules):
    out = [m for m in LOAD_ORDER if m in modules]
    return out + [m for m in modules if m not in out]


def registration(mods, features):
    fastmem, guard_gen, fpx = bool(features & 1), bool(features & 2), bool(features & 4)
    o = ['/* auto-generated by switchpiler (same contract as suyu game export) - DO NOT EDIT */\n',
         '/* Lists this game\'s statically linked recompiled modules in NSO load\n'
         '   order. Consumed by src/suyu_cmd/suyu.cpp. */\n',
         '#include <stdint.h>\n\n', 'typedef void (*SuyuRecompBlockFn)(void*);\n\n']
    for m in mods:
        o += [f'extern SuyuRecompBlockFn recomp_image_lookup_{m}(uint64_t);\n',
              f'extern unsigned recomp_image_guard_v2_{m}(unsigned);\n',
              f'extern unsigned recomp_image_abi_{m}(void);\n',
              f'extern void recomp_image_run_slice_{m}(void*);\n',
              f'extern void recomp_image_set_base_{m}(uint64_t);\n',
              f'extern uint64_t g_module_base_{m};\n']
    o.append('\ntypedef struct {\n    const char* name;\n    SuyuRecompBlockFn (*lookup)(uint64_t);\n'
             '    void (*set_base)(uint64_t);\n    SuyuRecompBlockFn run_slice;\n'
             '    unsigned (*image_abi)(void);\n} SuyuRecompStaticModule;\n\n'
             'const SuyuRecompStaticModule* suyu_recomp_static_modules_v4(unsigned* count);\n'
             'int suyu_recomp_static_guard_v2(unsigned version);\n\n'
             'static const SuyuRecompStaticModule s_modules[] = {\n')
    for m in mods:
        o.append(f'    {{ "{m}", recomp_image_lookup_{m}, recomp_image_set_base_{m}, '
                 f'recomp_image_run_slice_{m}, recomp_image_abi_{m} }},\n')
    o.append('};\n\nconst SuyuRecompStaticModule* suyu_recomp_static_modules_v4(unsigned* count) {\n'
             '    *count = (unsigned)(sizeof(s_modules) / sizeof(s_modules[0]));\n    return s_modules;\n}\n')
    o.append('int suyu_recomp_static_guard_v2(unsigned version) {\n  int ready=version==2;\n')
    o += [f'  if(recomp_image_guard_v2_{m}(0)!=2) ready=0;\n' for m in mods]
    o += [f'  recomp_image_guard_v2_{m}(ready?2:0);\n' for m in mods]
    o.append('  return ready;\n}\n')
    if fastmem:
        o.append('\n')
        for m in mods:
            o += [f'extern unsigned recomp_image_features_{m}(void);\n',
                  f'extern unsigned recomp_image_fastmem_v1_{m}(uint32_t, uint32_t, uint64_t, uint32_t, uint32_t);\n']
        o.append('int suyu_recomp_static_fastmem_v1(uint32_t, uint32_t, uint64_t, uint32_t, uint32_t);\n'
                 'int suyu_recomp_static_fastmem_v1(uint32_t page_bits, uint32_t stride_log2,\n'
                 '                                  uint64_t pointer_mask, uint32_t off_table,\n'
                 '                                  uint32_t off_limit) {\n  int ready=1;\n')
        o += [f'  if(!(recomp_image_features_{m}()&1u) || recomp_image_fastmem_v1_{m}'
              f'(page_bits,stride_log2,pointer_mask,off_table,off_limit)!=1) ready=0;\n' for m in mods]
        o.append('  return ready;\n}\nunsigned suyu_recomp_static_features_v1(void);\n'
                 'unsigned suyu_recomp_static_features_v1(void) {\n  unsigned f=0;\n')
        o += [f'  f|=recomp_image_features_{m}();\n' for m in mods]
        o.append('  return f;\n}\n')
    if guard_gen:
        o.append('\ntypedef struct { uint32_t* word; const uint64_t* base; '
                 'uint64_t code_lo, code_end; } SuyuRecompGuardGenModule;\n')
        o += [f'extern uint32_t* recomp_image_guard_gen_v1_{m}(uint32_t, uint64_t*, uint64_t*, const uint64_t**);\n'
              for m in mods]
        sig = ('unsigned suyu_recomp_static_guard_gen_v1(uint32_t host_version,\n'
               '                                         SuyuRecompGuardGenModule* out,\n'
               '                                         unsigned max)')
        o.append(sig + ';\n' + sig + ' {\n  unsigned n=0;\n' + f'  if(max<{len(mods)}u) return 0;\n')
        o += [f'  out[n].word=recomp_image_guard_gen_v1_{m}(host_version,&out[n].code_lo,&out[n].code_end,&out[n].base);\n'
              '  if(!out[n++].word) return 0;\n' for m in mods]
        o.append('  return n;\n}\n')
    if fpx:
        o.append('\n')
        o += [f'extern unsigned recomp_image_fpx_v1_{m}(uint32_t, uint32_t, uint64_t);\n' for m in mods]
        sig = ('unsigned suyu_recomp_static_fpx_v1(uint32_t off_fpcr, uint32_t off_fpsr,\n'
               '                                   uint64_t inhibit_bit)')
        o.append(sig + ';\n' + sig + ' {\n  unsigned r=0;\n')
        o += [f'  if(!(recomp_image_features_{m}()&4u)) return 0;\n'
              f'  r=recomp_image_fpx_v1_{m}(off_fpcr,off_fpsr,inhibit_bit);\n  if(!r) return 0;\n' for m in mods]
        o.append('  return r;\n}\n')
    return ''.join(o)


def write_markers(root, features):
    markers = {
        'recomp_abi_v4.h': ('/* ABI 4 registry includes nonrecursive slice and image ABI exports. */\n', True),
        'recomp_guard_v2.h': ('/* Separate guarded-code registration; legacy module registry ABI unchanged. */\n', True),
        'recomp_fastmem_v1.h': ('/* ABI 6 registry exports suyu_recomp_static_fastmem_v1. */\n', bool(features & 1)),
        'recomp_fpx_v1.h': ('/* ABI 6 registry exports suyu_recomp_static_fpx_v1. */\n', bool(features & 4)),
        'recomp_features_v1.h': ('/* ABI 6 registry exports suyu_recomp_static_features_v1. */\n', bool(features & 1)),
        'recomp_guard_gen_v1.h': ('/* ABI 6 registry exports suyu_recomp_static_guard_gen_v1. */\n', bool(features & 2)),
    }
    for name, (text, wanted) in markers.items():
        path = root / name
        if wanted:
            path.write_text(text)
        elif path.exists():
            path.unlink()


GLSLANG_TAG = '16.5.0'  # same tools as upstream scripts/bootstrap.ps1
GLSLANG_SHA256 = '06b71298b750268c127f2ee7ae0ef7525e2068120c6c8a3a08b2f58ca6f325ce'
QT_VERSION = '6.9.3'


def windows_tools():
    """glslang and an MSVC build of Qt (with Charts), fetched once into local/tools like upstream does."""
    import urllib.request
    import zipfile
    tools = ROOT / 'local/tools'
    glslang = tools / 'glslang/bin/glslang.exe'
    if not glslang.exists():
        name = f'glslang-{GLSLANG_TAG}-windows-x86_64-release.zip'
        archive = tools / name
        tools.mkdir(parents=True, exist_ok=True)
        print(f'downloading {name}', flush=True)
        urllib.request.urlretrieve(
            f'https://github.com/KhronosGroup/glslang/releases/download/{GLSLANG_TAG}/{name}', archive)
        import hashlib
        if hashlib.sha256(archive.read_bytes()).hexdigest() != GLSLANG_SHA256:
            archive.unlink()
            sys.exit(f'{name}: checksum mismatch, refusing to use it')
        with zipfile.ZipFile(archive) as z:
            z.extractall(tools / 'glslang')
    qt = tools / f'Qt/{QT_VERSION}/msvc2022_64'
    if not qt.exists():
        pydeps = tools / 'pydeps'
        subprocess.run([sys.executable, '-m', 'pip', 'install', '--quiet', '--target', str(pydeps), 'aqtinstall'],
                       check=True)
        env = dict(os.environ, PYTHONPATH=str(pydeps))
        subprocess.run([sys.executable, '-m', 'aqt', 'install-qt', 'windows', 'desktop', QT_VERSION,
                        'win64_msvc2022_64', '-m', 'qtcharts', '-O', str(tools / 'Qt')], check=True, env=env)
    return glslang, qt


def build_modules_clang_cl(src, build, exefs, mods, env, recomp_jobs):
    """Windows: compile the generated modules with clang-cl (upstream's src/suyu_cmd/recomp_modules project).

    Returns the folder of the resulting .lib files, for SUYU_CMD_RECOMP_PREBUILT_DIR."""
    modules = [m for m in mods if (exefs / m / 'CMakeLists.txt').exists()]
    out = build / 'recomp_clang'
    meter = ROOT / 'scripts/compile-meter.py'
    configure = ['cmake', '-G', 'Ninja', '-S', src / 'src/suyu_cmd/recomp_modules', '-B', out,
                 '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_C_COMPILER=clang-cl',
                 f'-DCMAKE_C_COMPILER_LAUNCHER={Path(sys.executable).as_posix()};{meter.as_posix()}',
                 f'-DSUYU_CMD_RECOMP_DIR={exefs.as_posix()}', f'-DSUYU_RECOMP_MODULES={";".join(modules)}',
                 f'-DRECOMP_JOBS={recomp_jobs}']
    log = ROOT / 'artifacts/recomp-clang-configure.log'
    with log.open('w') as f:
        if subprocess.run([str(c) for c in configure], cwd=ROOT, env=env, stdout=f, stderr=subprocess.STDOUT).returncode:
            sys.exit(f'clang-cl module project did not configure (see {log.relative_to(ROOT)})')
    log = ROOT / 'artifacts/recomp-clang-build.log'
    with log.open('w') as f:
        for m in modules:
            print(f'compiling module {m} with clang-cl', flush=True)
            if subprocess.run(['cmake', '--build', str(out), '--target', f'recomp_static_{m}'], cwd=ROOT, env=env,
                              stdout=f, stderr=subprocess.STDOUT).returncode:
                sys.exit(f'module {m} did not compile (see {log.relative_to(ROOT)})')
    return (out / 'lib').as_posix()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--hybrid', action='store_true', help='keep a JIT fallback (default: strict, no JIT)')
    parser.add_argument('--jobs', type=int, default=4)
    parser.add_argument('--recomp-jobs', type=int, default=2, help='concurrent generated-C compiles (RAM-bound)')
    parser.add_argument('--configure-only', action='store_true')
    parser.add_argument('--backend-only', action='store_true',
                        help='build suyu + suyu-cmd in the same no-JIT tree (no game modules yet): the tools for dump/export')
    parser.add_argument('--mem-budget-mb', type=int, default=0,
                        help='memory-aware scheduling of generated-C compiles (use with a wide --recomp-jobs)')
    args = parser.parse_args()

    exefs = None
    if not args.backend_only:
        # <name>.AppDir/usr/bin/aot_cache on Linux; the Windows export uses another folder layout
        export = next(p for p in (ROOT / 'local/aot' / lab.export_name()).rglob('aot_cache')
                      if (p / 'aot_manifest.json').exists())
        manifest = json.loads((export / 'aot_manifest.json').read_text())
        exefs = export / 'exefs'
        mods = ordered([m['name'] for m in manifest['modules']])
        features = manifest['image_features']
        (exefs / 'recomp_registration.c').write_text(registration(mods, features))
        write_markers(exefs, features)
        print(f'registry: {", ".join(mods)} (ABI {manifest["image_abi"]}, features {features})')

    name = 'suyu-static' + ('-hybrid' if args.hybrid else '')
    build = ROOT / f'upstream/mk8-recomp/build/{name}'
    src = ROOT / 'upstream/mk8-recomp/third_party/suyu'
    deps = ROOT / 'local/deps/usr'
    (ROOT / 'artifacts').mkdir(exist_ok=True)
    env = os.environ.copy()
    env['COMPILE_METER_LOG'] = str(ROOT / f'artifacts/{name}-compile.tsv')
    env['COMPILE_OBJ_CACHE'] = str(ROOT / 'local/aot/objcache')
    if args.mem_budget_mb:
        env['COMPILE_MEM_BUDGET_MB'] = str(args.mem_budget_mb)
    meter = ROOT / 'scripts/compile-meter.py'
    prebuilt = ''
    if plat.IS_WINDOWS:
        # suyu is built with MSVC, as upstream does. CMake allows one C compiler per project, so the game's
        # generated C is compiled with clang-cl in a project of its own and linked in as prebuilt libraries.
        glslang, qt = windows_tools()
        toolchain = [f'-DQt6_DIR={qt.as_posix()}', f'-DCMAKE_PREFIX_PATH={qt.as_posix()}']
        if exefs:
            prebuilt = build_modules_clang_cl(src, build, exefs, mods, env, args.recomp_jobs)
    else:
        glslang = shutil.which('glslangValidator')
        toolchain = [*([f'-DCMAKE_PREFIX_PATH={deps}'] if deps.is_dir() else []),
                     f'-DCMAKE_C_COMPILER={shutil.which("clang")}', f'-DCMAKE_C_COMPILER_LAUNCHER={meter}']
    configure = ['cmake', '-S', src, '-B', build, '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=Release', *toolchain,
                 '-DENABLE_QT=ON', '-DYUZU_USE_BUNDLED_QT=OFF',
                 f'-DGLSLANGVALIDATOR={glslang}', '-DYUZU_CMD=ON', '-DYUZU_TESTS=OFF',
                 '-DENABLE_WEB_SERVICE=OFF', '-DYUZU_ROOM=OFF', '-DYUZU_ROOM_STANDALONE=OFF',
                 '-DENABLE_QT_TRANSLATION=OFF', '-DUSE_DISCORD_PRESENCE=OFF', '-Dfmt_FORCE_BUNDLED=ON',
                 f'-DSUYU_NO_JIT={"OFF" if args.hybrid else "ON"}',
                 f'-DSUYU_RECOMP_HYBRID={"ON" if args.hybrid else "OFF"}',
                 # Added later in the same tree: adding the game's modules only adds targets, the C++ is reused.
                 *([f'-DSUYU_CMD_RECOMP_DIR={exefs.as_posix()}', f'-DSUYU_CMD_RECOMP_PREBUILT_DIR={prebuilt}'] if exefs else []),
                 f'-DRECOMP_JOBS={args.recomp_jobs}']
    stage = 'backend' if args.backend_only else 'game'
    log = ROOT / f'artifacts/{name}-{stage}-configure.log'
    with log.open('w') as out:
        rc = subprocess.run([str(c) for c in configure], cwd=ROOT, env=env, stdout=out, stderr=subprocess.STDOUT).returncode
    if rc:
        sys.exit(f'configure failed (see {log.relative_to(ROOT)})')
    if args.configure_only:
        print(f'configured {build.relative_to(ROOT)}')
        return 0
    targets = ['suyu', 'suyu-cmd'] if args.backend_only else ['suyu-cmd-static']
    log = ROOT / f'artifacts/{name}-{stage}-build.log'
    with log.open('w') as out:
        rc = subprocess.run(['cmake', '--build', str(build), '--target', *targets, '--', f'-j{args.jobs}'],
                            cwd=ROOT, env=env, stdout=out, stderr=subprocess.STDOUT).returncode
    if args.backend_only:
        print(f'build rc={rc}; tools in {(build / "bin").relative_to(ROOT)}')
        return rc
    exe = build / f'bin/suyu-cmd-static{plat.EXE}'
    print(f'build rc={rc}; executable: {exe if exe.exists() else "missing"}')
    return rc


if __name__ == '__main__':
    sys.exit(main())
